### ISSUE TITLE
correlative paper

### ISSUE THREAD

**Issue by ghost** [XuHg-zjcn/Spectrum-Transform#2]
Hello. Thank you for your excellent code. Do you have the relevant papers to study?

**Comment by XuHg-zjcn** [comment]
I'm seldom to read papers, the model is reference by pix2pix, U-Net and MobileNet v2, you can search this papers

**Comment by ghost** [comment]
> I'm seldom to read papers, the model is reference by pix2pix, U-Net and MobileNet v2, you can search this papers

Thanks a lot.
